name: Events exercices

on:
  push:
      branches: 
        - "dev"
        - "feat/*"
        - "!staging" 
      paths:
        - "**.ts"

  pull_request:
    types: 
      - opened
      - closed

  schedule:
    - cron: '* * * * *' # Every minutes
    - cron: '0 3 * * 2' #Every Tuesday at 3am
    - cron: '30 */1 * * *'  #Every 1h30min  

  workflow_dispatch:

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)