on:
  workflow_dispatch:

jobs:
  print-event:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - with:
        node-version: [12, 14, 16]
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)